export enum WeatherInterface {
    "Sereno" = 0,
    "Leggermente nuovoloso" = 1,
    "Alcune nuovole ma sereno" = 2,
    "Nuvoloso" = 3,
    "Nebbioso" = 45,
    "Nebbia ghiacciante" = 48,
    "Piogerella leggera" = 51,
    "Piogerrella di media intensità" = 53,
    "Piogerella intensa" = 55,
    "Piogerella ghiacciata leggera" = 56,
    "Piogerella giacciata densa" = 57,
    "Pioggia leggera" = 61,
    "Pioggia media" = 63,
    "Pioggia forte" = 65,
    "Pioggia ghiacciata leggera" = 66,
    "Pioggia ghiacciata forte" = 67,
    "Neve debole" = 71,
    "Neve moderata" = 73,
    "Neve forte" = 75,
    "Neve a grani" = 77,
    "Acquazzoni leggeri" = 80,
    "Acquazzoni moderati" = 81,
    "Acquazzoni violenti" = 82,
    "Blizzards deboli" = 85,
    "Blizzards forti" = 86,
    "Temporali deboli o moderati" = 95,
}
