export enum WeatherInterface {
    "Clear sky" = 0,
    "Cloudy" = 1,
    "Clouds" = 2,
    "Cloudy Weather" = 3,
    "Fog" = 45,
    "depositing rime fog" = 48,
    "Drizzle: Light" = 51,
    "Drizzle: moderate" = 53,
    "Drizzle: Dense intensity" = 55,
    "Freezing Drizzle: Light" = 56,
    "Freezing Drizzle: Dense intensity" = 57,
    "Rain: slight" = 61,
    "Rain: moderate" = 63,
    "Rain: heavy" = 65,
    "Freezing Rain: Light" = 66,
    "Freezing Rain: heavy intensity" = 67,
    "Snow fall: Slight" = 71,
    "Snow fall: moderate" = 73,
    "Snow fall: heavy" = 75,
    "Snow grains" = 77,
    "Rain showers: Slight" = 80,
    "Rain showers: moderate" = 81,
    "Rain showers: violent" = 82,
    "Snow showers slight" = 85,
    "Snow showers heavy" = 86,
    "Thunderstorm: Slight or moderate" = 95,
}
